//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimonsRelocalizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimonsRelocalizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks Existor for the graphics!
        ///Thanks xpaperclip for the SC2Archive files!
        ///Thanks apocalypse_ua for packing the icon!
        ///
        ///Author: Simon Liang
        ///August 2012.
        /// </summary>
        internal static string aboutMessage {
            get {
                return ResourceManager.GetString("aboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者：梁皓然
        ///美工：Existor
        ///2012年8月.
        /// </summary>
        internal static string aboutMessageChinese {
            get {
                return ResourceManager.GetString("aboutMessageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have xxxx voice asset downloaded. Do you still want to use this asset?
        ///
        ///Choose &apos;Yes&apos; to proceed to download the asset.
        ///Choose &apos;No&apos; to revert your seletion..
        /// </summary>
        internal static string assetNotFoundMessage {
            get {
                return ResourceManager.GetString("assetNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你没有xxxx版本的语音包。
        ///
        ///点击&quot;Yes&quot;进行下载
        ///点击&quot;No&quot;返回界面重新选择.
        /// </summary>
        internal static string assetNotFoundMessageChinese {
            get {
                return ResourceManager.GetString("assetNotFoundMessageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Relocalize&apos; to download asset xxxx! -------&gt;.
        /// </summary>
        internal static string buttonAssetNotFoundHint {
            get {
                return ResourceManager.GetString("buttonAssetNotFoundHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击&quot;Relocalize&quot;按钮来下载xxxx语音包 ----&gt;.
        /// </summary>
        internal static string buttonAssetNotFoundHintChinese {
            get {
                return ResourceManager.GetString("buttonAssetNotFoundHintChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Ping....
        /// </summary>
        internal static string checkingPingMessage {
            get {
                return ResourceManager.GetString("checkingPingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在检查Ping....
        /// </summary>
        internal static string checkingPingMessageChinese {
            get {
                return ResourceManager.GetString("checkingPingMessageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Click me!.
        /// </summary>
        internal static string clickMe {
            get {
                return ResourceManager.GetString("clickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  点这里下载.
        /// </summary>
        internal static string clickMeChinese {
            get {
                return ResourceManager.GetString("clickMeChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Settings.
        /// </summary>
        internal static string hideSettings {
            get {
                return ResourceManager.GetString("hideSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏设置.
        /// </summary>
        internal static string hideSettingsChinese {
            get {
                return ResourceManager.GetString("hideSettingsChinese", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap icon_by_existor {
            get {
                object obj = ResourceManager.GetObject("icon_by_existor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2013 Haoran Liang
        ///
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///The above copyright notice and this permi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MITLicenseMessage {
            get {
                return ResourceManager.GetString("MITLicenseMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap new_new_relocalize_button {
            get {
                object obj = ResourceManager.GetObject("new_new_relocalize_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap relocalization {
            get {
                object obj = ResourceManager.GetObject("relocalization", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocalization from aaaa to bbbb with asset from cccc to dddd is finished! Enjoy!.
        /// </summary>
        internal static string relocalizationFinishedMessage {
            get {
                return ResourceManager.GetString("relocalizationFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序已完成跨区操作! 谢谢!.
        /// </summary>
        internal static string relocalizationFinishedMessageChinese {
            get {
                return ResourceManager.GetString("relocalizationFinishedMessageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocalizer up to date!.
        /// </summary>
        internal static string relocalizerUpToDateText {
            get {
                return ResourceManager.GetString("relocalizerUpToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件已是最新版本!.
        /// </summary>
        internal static string relocalizerUpToDateTextChinese {
            get {
                return ResourceManager.GetString("relocalizerUpToDateTextChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know the SC2 Installation Location!.
        /// </summary>
        internal static string SC2LocationNotFoundMessage {
            get {
                return ResourceManager.GetString("SC2LocationNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请提供星际2安装路径！.
        /// </summary>
        internal static string SC2LocationNotFoundMessageChinese {
            get {
                return ResourceManager.GetString("SC2LocationNotFoundMessageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know the SC2 Variable.txt Location!.
        /// </summary>
        internal static string SC2VarTXTLocationNotFoundMessage {
            get {
                return ResourceManager.GetString("SC2VarTXTLocationNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请提供Variable.txt路径(一般在我的文档下StarCraft II目录下).
        /// </summary>
        internal static string SC2VarTXTLocationNotFoundMessageChinese {
            get {
                return ResourceManager.GetString("SC2VarTXTLocationNotFoundMessageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Settings.
        /// </summary>
        internal static string showSettings {
            get {
                return ResourceManager.GetString("showSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示设置.
        /// </summary>
        internal static string showSettingsChinese {
            get {
                return ResourceManager.GetString("showSettingsChinese", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ui_text {
            get {
                object obj = ResourceManager.GetObject("ui_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available! New Version .
        /// </summary>
        internal static string updateAvailableText {
            get {
                return ResourceManager.GetString("updateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新版本 .
        /// </summary>
        internal static string updateAvailableTextChinese {
            get {
                return ResourceManager.GetString("updateAvailableTextChinese", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap voice_asset {
            get {
                object obj = ResourceManager.GetObject("voice_asset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait till download to finish before relocalizing again..
        /// </summary>
        internal static string waitForDownloadMessage {
            get {
                return ResourceManager.GetString("waitForDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请等待下载完成再重新跨区，以免程序破坏星际2程序文件.
        /// </summary>
        internal static string waitForDownloadMessageChinese {
            get {
                return ResourceManager.GetString("waitForDownloadMessageChinese", resourceCulture);
            }
        }
    }
}
