//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimonsRelocalizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimonsRelocalizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relocalizer is not in the SC2 installation folder!
        ///Please put the relocalizer into your SC2 installation folder first!
        ///The program will now close..
        /// </summary>
        internal static string Form1_Form1_Load_WrongFolderMessage {
            get {
                return ResourceManager.GetString("Form1_Form1_Load_WrongFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the browser pops up, please right click on the page and choose &apos;save as&apos;.
        ///Or you can copy the text and put it into a text file with notepad, and rename it as &apos;regions.xml&apos;.
        ///Make sure you put this file under the SC2 installation path, just like the relocalizer..
        /// </summary>
        internal static string LocaleChanger_AddRegionsXML_Message {
            get {
                return ResourceManager.GetString("LocaleChanger_AddRegionsXML_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the permission for the relocalizer to put in regions.xml.
        ///Do you want to manually download regions.xml and put it under the SC2 installation path?.
        /// </summary>
        internal static string LocaleChanger_AddRegionsXML_Warning {
            get {
                return ResourceManager.GetString("LocaleChanger_AddRegionsXML_Warning", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap new_new_relocalize_button {
            get {
                object obj = ResourceManager.GetObject("new_new_relocalize_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
