""" Relocalizer.py --

 UI generated by GUI Builder Build 146 on 2012-08-09 23:03:42 from:
    C:/Users/Simon/Desktop/development/SC2Patch150Relocalizer/SimonsRelocalizerPython/Relocalizer.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from Relocalizer_ui import Relocalizer

# BEGIN USER CODE global

# END USER CODE global

class CustomRelocalizer(Relocalizer):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _ComboBox_3_selectioncommand --
    #
    # Callback to handle _ComboBox_3 widget option -selectioncommand
    def _ComboBox_3_selectioncommand(self, *args):
        pass

    # _ComboBox_4_selectioncommand --
    #
    # Callback to handle _ComboBox_4 widget option -selectioncommand
    def _ComboBox_4_selectioncommand(self, *args):
        pass

    # buttonRelocalize_command --
    #
    # Callback to handle buttonRelocalize widget option -command
    def buttonRelocalize_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomRelocalizer(root)
    root.title('Relocalizer')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
