""" Relocalizer_ui.py --

 UI generated by GUI Builder Build 146 on 2012-08-09 23:03:42 from:
    C:/Users/Simon/Desktop/development/SC2Patch150Relocalizer/SimonsRelocalizerPython/Relocalizer.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Pmw
import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Relocalizer(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):
        self._images.append(Tkinter.PhotoImage('resources/relocalization.GIF', file = os.path.dirname(__file__) + '/resources/relocalization.GIF'))
        self._images.append(Tkinter.PhotoImage('resources/relocalize_button.GIF', file = os.path.dirname(__file__) + '/resources/relocalize_button.GIF'))
        self._images.append(Tkinter.PhotoImage('resources/voice_asset.GIF', file = os.path.dirname(__file__) + '/resources/voice_asset.GIF'))


        # Widget Initialization
        self.labelLocale = Tkinter.Label(root,
            justify = "left",
            text = "locale:",
        )
        self.labelAsset = Tkinter.Label(root,
            justify = "left",
            text = "asset:",
        )
        self.buttonRelocalize = Tkinter.Button(root,
            height = 169,
            image = "resources/relocalize_button.GIF",
            text = "Relocalize!",
            width = 195,
        )
        self.labelGlobe = Tkinter.Label(root,
            image = "resources/relocalization.GIF",
            text = "globe",
        )
        self.labelSpeaker = Tkinter.Label(root,
            image = "resources/voice_asset.GIF",
            text = "speaker",
        )
        self._ComboBox_3 = Pmw.ComboBox(root,
        )
        self._ComboBox_4 = Pmw.ComboBox(root,
        )
        self.menu = Tkinter.Menu(root,
        )

        # widget commands

        self.buttonRelocalize.configure(
            command = self.buttonRelocalize_command
        )
        self._ComboBox_3.configure(
            selectioncommand = self._ComboBox_3_selectioncommand
        )
        self._ComboBox_4.configure(
            selectioncommand = self._ComboBox_4_selectioncommand
        )
        self.menuitem3 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "versions",
            menu = self.menuitem3,
        )
        self.menuitem6 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = u"\u6C49\u5316",
            menu = self.menuitem6,
        )
        self.menuitem7 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "About",
            menu = self.menuitem7,
        )
        self.menuitem7.add_command(
            label = "Teamliquid Page",
        )
        self.menuitem7.add_command(
            label = "PLU Page",
        )
        self.menuitem7.add_command(
            label = "Project Page",
        )
        self.menuitem7.add_separator(
        )
        self.menuitem7.add_command(
            label = "MIT License",
        )
        self.menuitem7.add_command(
            label = "Buy me a beer!",
        )
        self.menuitem7.add_command(
            label = "About",
        )


        # Geometry Management
        self.labelLocale.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.labelAsset.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.buttonRelocalize.grid(
            in_    = root,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 5,
            sticky = ""
        )
        self.labelGlobe.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.labelSpeaker.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._ComboBox_3.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._ComboBox_4.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 2,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 6, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 5, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 10, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 12, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 10, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 42, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 21, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 98, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 193, pad = 0)
        root.configure(menu = self.menu)


